## NumPy Practice Questions:
1. Array Creation: Create a NumPy array of integers from 1 to 10.
2. Array Operations: Perform element-wise addition, subtraction, multiplication, and
division on two NumPy arrays.
3. Array Slicing: Extract the first three elements from a NumPy array.
4. Array Reshaping: Reshape a 1D NumPy array into a 2D array with 2 rows and 3
columns.
5. Array Aggregation: Calculate the mean, median, and standard deviation of a NumPy
array

In [22]:
# 1. Array Creation: Create a NumPy array of integers from 1 to 10.

import numpy as np

arr1 = np.arange(1, 11, 1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
# 2. Array Operations: Perform element-wise addition, subtraction, multiplication, and division on two NumPy arrays.

arr2 = np.array([3, 5, 6, 6, 9, 29, 7, 29, 5, 1])

arr3 = arr1 + arr2
print(arr3)

arr4 = arr1 - arr2
print(arr4)

arr5 = arr1 * arr2
print(arr5)

arr6 = arr2 / arr2
print(arr6)

[ 4  7  9 10 14 35 14 37 14 11]
[ -2  -3  -3  -2  -4 -23   0 -21   4   9]
[  3  10  18  24  45 174  49 232  45  10]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
# 3. Array Slicing: Extract the first three elements from a NumPy array.

arr7 = arr1[3:]
print(arr7)

[ 4  5  6  7  8  9 10]


In [25]:
# 4. Array Reshaping: Reshape a 1D NumPy array into a 2D array with 2 rows and 3 columns.

arr8 = arr1[4:].reshape(2, 3)
print(arr8)

[[ 5  6  7]
 [ 8  9 10]]


In [26]:
# 5. Array Aggregation: Calculate the mean, median, and standard deviation of a NumPy array

mean = np.mean(arr1)
print(mean)

median = np.median(arr1)
print(median)

std = np.std(arr1)
print(std)

5.5
5.5
2.8722813232690143
